version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    working_dir: /app
    command: >
      sh -lc '
        # Se não existe uma app ainda, cria (opcional)
        if [ ! -f /app/config/application.rb ]; then
          echo "Criando nova aplicação Rails..."
          gem list -i rails >/dev/null || gem install rails -N
          rails new . --force --database=sqlite3 --skip-git
        fi &&
        bundle install &&
        rm -f tmp/pids/server.pid &&
        bundle exec rails db:prepare &&
        bundle exec rails server -b 0.0.0.0 -p 3000
      '

volumes:
  bundle_cache:
