version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
    stdin_open: true
    tty: true
    # Para Windows, usar bash explicitamente
    command: >
      bash -c "
        if [ ! -f /app/config/application.rb ]; then
          echo 'Criando nova aplicação Rails...'
          rails new . --force --database=sqlite3 --skip-git
        fi &&
        bundle install &&
        rails server -b 0.0.0.0 -p 3000
      "

volumes:
  bundle_cache: